blueprint:
  name: Kamera Bewegung Benachrichtigung mit Titel & Snapshot
  description: |
    Sendet eine Benachrichtigung mit Titel und Bild von der Kamera, die eine Bewegung erkannt hat.
    Kamera wird automatisch abgeleitet aus dem Sensor, z. B. `binary_sensor.kamera_terrasse_motion` → `camera.kamera_terrasse`
  domain: automation

  input:
    included_sensors:
      name: Kamera-Bewegungssensoren
      description: Diese Sensoren lösen die Benachrichtigung aus
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
          multiple: true

    excluded_sensors:
      name: Ausgeschlossene Sensoren
      description: Diese Sensoren werden ignoriert
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    notify_device:
      name: Zielgerät
      description: Gerät, an das die Benachrichtigung gesendet wird
      selector:
        device:
          integration: mobile_app

    notify_title:
      name: Nachrichtentitel
      description: Titel der Benachrichtigung. Du kannst Variablen wie {{ trigger.entity_id }} verwenden.
      default: Bewegung erkannt!
      selector:
        text:

    notify_message:
      name: Nachrichtentext
      description: Text der Nachricht. Du kannst Variablen wie {{ trigger.entity_id }} verwenden.
      default: Es wurde Bewegung erkannt bei {{ trigger.entity_id }}
      selector:
        text:

    notify_level:
      name: Benachrichtigungsstil
      description: Ton, Lautstärke oder Lautlos
      default: normal
      selector:
        select:
          options:
            - normal
            - kritisch
            - lautlos

mode: parallel

trigger:
  - platform: state
    entity_id: !input included_sensors
    to: "on"

condition:
  - condition: template
    value_template: >
      {{ trigger.entity_id not in (inputs.excluded_sensors | default([])) }}

variables:
  notify_service: >
    notify.mobile_app_{{ device_attr(notify_device, 'name') | lower | replace(" ", "_") }}
  message: "{{ notify_message }}"
  title: "{{ notify_title }}"
  sensor_entity: "{{ trigger.entity_id }}"
  camera_entity: >
    {{ 'camera.' + sensor_entity.split('.')[1].replace('_motion','').replace('_occupancy','') }}
  snapshot_path: "/config/www/snapshots/{{ camera_entity | replace('.', '_') }}.jpg"
  snapshot_url: "{{ snapshot_path | replace('/config/www', '/local') }}"

action:
  - service: camera.snapshot
    data:
      entity_id: "{{ camera_entity }}"
      filename: "{{ snapshot_path }}"

  - delay: "00:00:01"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ notify_level == 'kritisch' }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              title: "{{ title }}"
              message: "{{ message }}"
              data:
                push:
                  sound:
                    name: default
                    critical: 1
                    volume: 1.0
                image: "{{ snapshot_url }}"
      - conditions:
          - condition: template
            value_template: "{{ notify_level == 'lautlos' }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              title: "{{ title }}"
              message: "{{ message }}"
              data:
                push:
                  sound: none
                image: "{{ snapshot_url }}"
    default:
      - service: "{{ notify_service }}"
        data:
          title: "{{ title }}"
          message: "{{ message }}"
          data:
            image: "{{ snapshot_url }}"