blueprint:
  name: Ring Intercom – Klingelbenachrichtigung (hausture_ding + TTS + Push + Zeit)
  description: >
    Reagiert auf das benutzerdefinierte Event `hausture_ding` von deiner Ring Intercom
    und gibt eine TTS-Nachricht auf Lautsprechern aus + Push-Benachrichtigung, nur zu definierten Zeiten.
  domain: automation
  input:
    media_players:
      name: Lautsprecher (TTS-Ziel)
      description: Wähle die Lautsprecher, auf denen die Nachricht abgespielt wird (z. B. HomePods)
      selector:
        target:
          entity:
            domain: media_player

    tts_service:
      name: TTS-Service
      description: Wähle den TTS-Dienst (z. B. tts.google_say)
      default: tts.google_say
      selector:
        text:

    tts_message:
      name: TTS-Nachricht
      description: Nachricht, die bei Klingeln gesprochen wird
      default: "Es hat jemand an der Haustür geklingelt!"
      selector:
        text:

    notify_device:
      name: Push-Gerät
      description: Gerät mit Home Assistant App für Push-Benachrichtigung
      selector:
        device:
          integration: mobile_app

    push_message:
      name: Push-Nachricht
      description: Nachricht, die ans Mobilgerät geschickt wird
      default: "Klingel: Es hat jemand an der Haustür geklingelt."
      selector:
        text:

    start_time:
      name: Startzeit
      description: Frühester Zeitpunkt, zu dem die Benachrichtigung erfolgen darf
      default: "07:00:00"
      selector:
        time:

    end_time:
      name: Endzeit
      description: Spätester Zeitpunkt, bis zu dem Benachrichtigungen erlaubt sind
      default: "22:00:00"
      selector:
        time:

trigger:
  - platform: event
    event_type: hausture_ding

condition:
  - condition: time
    after: !input start_time
    before: !input end_time

action:
  - variables:
      media_player_entities: "{{ expand(targets.media_players) | map(attribute='entity_id') | list }}"
  - repeat:
      for_each: "{{ media_player_entities }}"
      sequence:
        - service: !input tts_service
          data:
            entity_id: "{{ repeat.item }}"
            message: !input tts_message

  - service: notify.notify
    data:
      message: !input push_message
      target:
        - !input notify_device

mode: single
