blueprint:
  name: Ring Intercom – Klingelbenachrichtigung (TTS + Push + Zeit)
  description: >
    Gibt bei einem Klingelereignis eine Benachrichtigung über HomePods (TTS) und sendet eine Push-Mitteilung – optional mit Zeitfenster.
  domain: automation
  input:
    ring_sensor:
      name: Klingelsensor
      description: Entität, die das Klingeln meldet (z. B. binary_sensor.ring_klingel)
      selector:
        entity:
          domain: binary_sensor

    media_players:
      name: Lautsprecher (z. B. HomePods)
      description: Wähle die Geräte aus, auf denen die Audio-Nachricht abgespielt wird.
      selector:
        target:
          entity:
            domain: media_player

    tts_service:
      name: TTS-Service
      description: Wähle den TTS-Service (z. B. tts.google_say)
      default: tts.google_say
      selector:
        text:

    tts_message:
      name: TTS-Nachricht
      description: Was soll über die Lautsprecher gesagt werden?
      default: "Es hat jemand an der Tür geklingelt!"
      selector:
        text:

    notify_device:
      name: Mobilgerät für Push
      description: Gerät mit Home Assistant App für Push-Mitteilung
      selector:
        device:
          integration: mobile_app

    push_message:
      name: Push-Nachricht
      description: Nachricht, die als Push versendet wird
      default: "Klingel: Es hat jemand an der Tür geklingelt."
      selector:
        text:

    start_time:
      name: Startzeit (aktiv ab)
      default: "07:00:00"
      selector:
        time:

    end_time:
      name: Endzeit (aktiv bis)
      default: "22:00:00"
      selector:
        time:

trigger:
  - platform: state
    entity_id: !input ring_sensor
    from: "off"
    to: "on"

condition:
  - condition: time
    after: !input start_time
    before: !input end_time

action:
  - repeat:
      for_each: "{{ expand(targets['media_players']) | map(attribute='entity_id') | list }}"
      sequence:
        - service: !input tts_service
          data:
            entity_id: "{{ repeat.item }}"
            message: !input tts_message

  - service: notify.mobile_app_{{ device_attr(!input notify_device, 'name') | lower | replace(' ', '_') }}
    data:
      message: !input push_message

mode: single
